// Code generated by ent, DO NOT EDIT.

package censor

import (
	"fmt"
	"haruki-database/database/schema/censor/namelog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// NameLog is the model entity for the NameLog schema.
type NameLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *string `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name *string `json:"name,omitempty"`
	// ImUserID holds the value of the "im_user_id" field.
	ImUserID *string `json:"im_user_id,omitempty"`
	// Time holds the value of the "time" field.
	Time *time.Time `json:"time,omitempty"`
	// Result holds the value of the "result" field.
	Result       *string `json:"result,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NameLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case namelog.FieldID:
			values[i] = new(sql.NullInt64)
		case namelog.FieldUserID, namelog.FieldName, namelog.FieldImUserID, namelog.FieldResult:
			values[i] = new(sql.NullString)
		case namelog.FieldTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NameLog fields.
func (_m *NameLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case namelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case namelog.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(string)
				*_m.UserID = value.String
			}
		case namelog.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case namelog.FieldImUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field im_user_id", values[i])
			} else if value.Valid {
				_m.ImUserID = new(string)
				*_m.ImUserID = value.String
			}
		case namelog.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				_m.Time = new(time.Time)
				*_m.Time = value.Time
			}
		case namelog.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = new(string)
				*_m.Result = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NameLog.
// This includes values selected through modifiers, order, etc.
func (_m *NameLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NameLog.
// Note that you need to call NameLog.Unwrap() before calling this method if this NameLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NameLog) Update() *NameLogUpdateOne {
	return NewNameLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NameLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NameLog) Unwrap() *NameLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("censor: NameLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NameLog) String() string {
	var builder strings.Builder
	builder.WriteString("NameLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImUserID; v != nil {
		builder.WriteString("im_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Time; v != nil {
		builder.WriteString("time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Result; v != nil {
		builder.WriteString("result=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// NameLogs is a parsable slice of NameLog.
type NameLogs []*NameLog
