// Code generated by ent, DO NOT EDIT.

package censor

import (
	"context"
	"errors"
	"fmt"
	"haruki-database/database/schema/censor/predicate"
	"haruki-database/database/schema/censor/shortbio"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShortBioUpdate is the builder for updating ShortBio entities.
type ShortBioUpdate struct {
	config
	hooks    []Hook
	mutation *ShortBioMutation
}

// Where appends a list predicates to the ShortBioUpdate builder.
func (_u *ShortBioUpdate) Where(ps ...predicate.ShortBio) *ShortBioUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ShortBioUpdate) SetUserID(v string) *ShortBioUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ShortBioUpdate) SetNillableUserID(v *string) *ShortBioUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ShortBioUpdate) ClearUserID() *ShortBioUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetContent sets the "content" field.
func (_u *ShortBioUpdate) SetContent(v string) *ShortBioUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ShortBioUpdate) SetNillableContent(v *string) *ShortBioUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ShortBioUpdate) ClearContent() *ShortBioUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetHarukiUserID sets the "haruki_user_id" field.
func (_u *ShortBioUpdate) SetHarukiUserID(v int) *ShortBioUpdate {
	_u.mutation.ResetHarukiUserID()
	_u.mutation.SetHarukiUserID(v)
	return _u
}

// SetNillableHarukiUserID sets the "haruki_user_id" field if the given value is not nil.
func (_u *ShortBioUpdate) SetNillableHarukiUserID(v *int) *ShortBioUpdate {
	if v != nil {
		_u.SetHarukiUserID(*v)
	}
	return _u
}

// AddHarukiUserID adds value to the "haruki_user_id" field.
func (_u *ShortBioUpdate) AddHarukiUserID(v int) *ShortBioUpdate {
	_u.mutation.AddHarukiUserID(v)
	return _u
}

// ClearHarukiUserID clears the value of the "haruki_user_id" field.
func (_u *ShortBioUpdate) ClearHarukiUserID() *ShortBioUpdate {
	_u.mutation.ClearHarukiUserID()
	return _u
}

// SetResult sets the "result" field.
func (_u *ShortBioUpdate) SetResult(v string) *ShortBioUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ShortBioUpdate) SetNillableResult(v *string) *ShortBioUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *ShortBioUpdate) ClearResult() *ShortBioUpdate {
	_u.mutation.ClearResult()
	return _u
}

// Mutation returns the ShortBioMutation object of the builder.
func (_u *ShortBioUpdate) Mutation() *ShortBioMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShortBioUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShortBioUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShortBioUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShortBioUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShortBioUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := shortbio.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`censor: validator failed for field "ShortBio.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := shortbio.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`censor: validator failed for field "ShortBio.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := shortbio.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`censor: validator failed for field "ShortBio.result": %w`, err)}
		}
	}
	return nil
}

func (_u *ShortBioUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shortbio.Table, shortbio.Columns, sqlgraph.NewFieldSpec(shortbio.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(shortbio.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(shortbio.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(shortbio.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(shortbio.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.HarukiUserID(); ok {
		_spec.SetField(shortbio.FieldHarukiUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHarukiUserID(); ok {
		_spec.AddField(shortbio.FieldHarukiUserID, field.TypeInt, value)
	}
	if _u.mutation.HarukiUserIDCleared() {
		_spec.ClearField(shortbio.FieldHarukiUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(shortbio.FieldResult, field.TypeString, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(shortbio.FieldResult, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shortbio.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShortBioUpdateOne is the builder for updating a single ShortBio entity.
type ShortBioUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShortBioMutation
}

// SetUserID sets the "user_id" field.
func (_u *ShortBioUpdateOne) SetUserID(v string) *ShortBioUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ShortBioUpdateOne) SetNillableUserID(v *string) *ShortBioUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ShortBioUpdateOne) ClearUserID() *ShortBioUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetContent sets the "content" field.
func (_u *ShortBioUpdateOne) SetContent(v string) *ShortBioUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ShortBioUpdateOne) SetNillableContent(v *string) *ShortBioUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ShortBioUpdateOne) ClearContent() *ShortBioUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetHarukiUserID sets the "haruki_user_id" field.
func (_u *ShortBioUpdateOne) SetHarukiUserID(v int) *ShortBioUpdateOne {
	_u.mutation.ResetHarukiUserID()
	_u.mutation.SetHarukiUserID(v)
	return _u
}

// SetNillableHarukiUserID sets the "haruki_user_id" field if the given value is not nil.
func (_u *ShortBioUpdateOne) SetNillableHarukiUserID(v *int) *ShortBioUpdateOne {
	if v != nil {
		_u.SetHarukiUserID(*v)
	}
	return _u
}

// AddHarukiUserID adds value to the "haruki_user_id" field.
func (_u *ShortBioUpdateOne) AddHarukiUserID(v int) *ShortBioUpdateOne {
	_u.mutation.AddHarukiUserID(v)
	return _u
}

// ClearHarukiUserID clears the value of the "haruki_user_id" field.
func (_u *ShortBioUpdateOne) ClearHarukiUserID() *ShortBioUpdateOne {
	_u.mutation.ClearHarukiUserID()
	return _u
}

// SetResult sets the "result" field.
func (_u *ShortBioUpdateOne) SetResult(v string) *ShortBioUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *ShortBioUpdateOne) SetNillableResult(v *string) *ShortBioUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *ShortBioUpdateOne) ClearResult() *ShortBioUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// Mutation returns the ShortBioMutation object of the builder.
func (_u *ShortBioUpdateOne) Mutation() *ShortBioMutation {
	return _u.mutation
}

// Where appends a list predicates to the ShortBioUpdate builder.
func (_u *ShortBioUpdateOne) Where(ps ...predicate.ShortBio) *ShortBioUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShortBioUpdateOne) Select(field string, fields ...string) *ShortBioUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ShortBio entity.
func (_u *ShortBioUpdateOne) Save(ctx context.Context) (*ShortBio, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShortBioUpdateOne) SaveX(ctx context.Context) *ShortBio {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShortBioUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShortBioUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShortBioUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := shortbio.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`censor: validator failed for field "ShortBio.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := shortbio.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`censor: validator failed for field "ShortBio.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := shortbio.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`censor: validator failed for field "ShortBio.result": %w`, err)}
		}
	}
	return nil
}

func (_u *ShortBioUpdateOne) sqlSave(ctx context.Context) (_node *ShortBio, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shortbio.Table, shortbio.Columns, sqlgraph.NewFieldSpec(shortbio.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`censor: missing "ShortBio.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shortbio.FieldID)
		for _, f := range fields {
			if !shortbio.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("censor: invalid field %q for query", f)}
			}
			if f != shortbio.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(shortbio.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(shortbio.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(shortbio.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(shortbio.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.HarukiUserID(); ok {
		_spec.SetField(shortbio.FieldHarukiUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHarukiUserID(); ok {
		_spec.AddField(shortbio.FieldHarukiUserID, field.TypeInt, value)
	}
	if _u.mutation.HarukiUserIDCleared() {
		_spec.ClearField(shortbio.FieldHarukiUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(shortbio.FieldResult, field.TypeString, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(shortbio.FieldResult, field.TypeString)
	}
	_node = &ShortBio{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shortbio.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
