// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// NameLog is the predicate function for namelog builders.
type NameLog func(*sql.Selector)

// Result is the predicate function for result builders.
type Result func(*sql.Selector)

// ShortBio is the predicate function for shortbio builders.
type ShortBio func(*sql.Selector)
