// Code generated by ent, DO NOT EDIT.

package bot

import (
	"haruki-database/database/schema/bot/dailyrequests"
	"haruki-database/database/schema/bot/hourlyrequests"
	"haruki-database/database/schema/bot/user"
	"haruki-database/entsrc/schema/bot/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dailyrequestsFields := schema.DailyRequests{}.Fields()
	_ = dailyrequestsFields
	// dailyrequestsDescCount is the schema descriptor for count field.
	dailyrequestsDescCount := dailyrequestsFields[1].Descriptor()
	// dailyrequests.DefaultCount holds the default value on creation for the count field.
	dailyrequests.DefaultCount = dailyrequestsDescCount.Default.(int)
	hourlyrequestsFields := schema.HourlyRequests{}.Fields()
	_ = hourlyrequestsFields
	// hourlyrequestsDescCount is the schema descriptor for count field.
	hourlyrequestsDescCount := hourlyrequestsFields[1].Descriptor()
	// hourlyrequests.DefaultCount holds the default value on creation for the count field.
	hourlyrequests.DefaultCount = hourlyrequestsDescCount.Default.(int)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCredential is the schema descriptor for credential field.
	userDescCredential := userFields[2].Descriptor()
	// user.CredentialValidator is a validator for the "credential" field. It is called by the builders before save.
	user.CredentialValidator = userDescCredential.Validators[0].(func(string) error)
}
