// Code generated by ent, DO NOT EDIT.

package userdefaultbinding

import (
	"haruki-database/database/schema/pjsk/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldLTE(FieldID, id))
}

// HarukiUserID applies equality check predicate on the "haruki_user_id" field. It's identical to HarukiUserIDEQ.
func HarukiUserID(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEQ(FieldHarukiUserID, v))
}

// Server applies equality check predicate on the "server" field. It's identical to ServerEQ.
func Server(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEQ(FieldServer, v))
}

// BindingID applies equality check predicate on the "binding_id" field. It's identical to BindingIDEQ.
func BindingID(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEQ(FieldBindingID, v))
}

// HarukiUserIDEQ applies the EQ predicate on the "haruki_user_id" field.
func HarukiUserIDEQ(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEQ(FieldHarukiUserID, v))
}

// HarukiUserIDNEQ applies the NEQ predicate on the "haruki_user_id" field.
func HarukiUserIDNEQ(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldNEQ(FieldHarukiUserID, v))
}

// HarukiUserIDIn applies the In predicate on the "haruki_user_id" field.
func HarukiUserIDIn(vs ...int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldIn(FieldHarukiUserID, vs...))
}

// HarukiUserIDNotIn applies the NotIn predicate on the "haruki_user_id" field.
func HarukiUserIDNotIn(vs ...int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldNotIn(FieldHarukiUserID, vs...))
}

// HarukiUserIDGT applies the GT predicate on the "haruki_user_id" field.
func HarukiUserIDGT(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldGT(FieldHarukiUserID, v))
}

// HarukiUserIDGTE applies the GTE predicate on the "haruki_user_id" field.
func HarukiUserIDGTE(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldGTE(FieldHarukiUserID, v))
}

// HarukiUserIDLT applies the LT predicate on the "haruki_user_id" field.
func HarukiUserIDLT(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldLT(FieldHarukiUserID, v))
}

// HarukiUserIDLTE applies the LTE predicate on the "haruki_user_id" field.
func HarukiUserIDLTE(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldLTE(FieldHarukiUserID, v))
}

// ServerEQ applies the EQ predicate on the "server" field.
func ServerEQ(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEQ(FieldServer, v))
}

// ServerNEQ applies the NEQ predicate on the "server" field.
func ServerNEQ(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldNEQ(FieldServer, v))
}

// ServerIn applies the In predicate on the "server" field.
func ServerIn(vs ...string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldIn(FieldServer, vs...))
}

// ServerNotIn applies the NotIn predicate on the "server" field.
func ServerNotIn(vs ...string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldNotIn(FieldServer, vs...))
}

// ServerGT applies the GT predicate on the "server" field.
func ServerGT(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldGT(FieldServer, v))
}

// ServerGTE applies the GTE predicate on the "server" field.
func ServerGTE(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldGTE(FieldServer, v))
}

// ServerLT applies the LT predicate on the "server" field.
func ServerLT(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldLT(FieldServer, v))
}

// ServerLTE applies the LTE predicate on the "server" field.
func ServerLTE(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldLTE(FieldServer, v))
}

// ServerContains applies the Contains predicate on the "server" field.
func ServerContains(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldContains(FieldServer, v))
}

// ServerHasPrefix applies the HasPrefix predicate on the "server" field.
func ServerHasPrefix(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldHasPrefix(FieldServer, v))
}

// ServerHasSuffix applies the HasSuffix predicate on the "server" field.
func ServerHasSuffix(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldHasSuffix(FieldServer, v))
}

// ServerEqualFold applies the EqualFold predicate on the "server" field.
func ServerEqualFold(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEqualFold(FieldServer, v))
}

// ServerContainsFold applies the ContainsFold predicate on the "server" field.
func ServerContainsFold(v string) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldContainsFold(FieldServer, v))
}

// BindingIDEQ applies the EQ predicate on the "binding_id" field.
func BindingIDEQ(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldEQ(FieldBindingID, v))
}

// BindingIDNEQ applies the NEQ predicate on the "binding_id" field.
func BindingIDNEQ(v int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldNEQ(FieldBindingID, v))
}

// BindingIDIn applies the In predicate on the "binding_id" field.
func BindingIDIn(vs ...int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldIn(FieldBindingID, vs...))
}

// BindingIDNotIn applies the NotIn predicate on the "binding_id" field.
func BindingIDNotIn(vs ...int) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.FieldNotIn(FieldBindingID, vs...))
}

// HasBinding applies the HasEdge predicate on the "binding" edge.
func HasBinding() predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BindingTable, BindingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBindingWith applies the HasEdge predicate on the "binding" edge with a given conditions (other predicates).
func HasBindingWith(preds ...predicate.UserBinding) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(func(s *sql.Selector) {
		step := newBindingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserDefaultBinding) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserDefaultBinding) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserDefaultBinding) predicate.UserDefaultBinding {
	return predicate.UserDefaultBinding(sql.NotPredicates(p))
}
