// Code generated by ent, DO NOT EDIT.

package users

import (
	"context"
	"errors"
	"fmt"
	"haruki-database/database/schema/users/predicate"
	"haruki-database/database/schema/users/user"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeUser = "User"
)

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                        Op
	typ                       string
	id                        *int
	platform                  *string
	user_id                   *string
	ban_state                 *bool
	ban_reason                *string
	pjsk_ban_state            *bool
	pjsk_ban_reason           *string
	chunithm_ban_state        *bool
	chunithm_ban_reason       *string
	pjsk_main_ban_state       *bool
	pjsk_main_ban_reason      *string
	pjsk_ranking_ban_state    *bool
	pjsk_ranking_ban_reason   *string
	pjsk_alias_ban_state      *bool
	pjsk_alias_ban_reason     *string
	pjsk_mysekai_ban_state    *bool
	pjsk_mysekai_ban_reason   *string
	chunithm_main_ban_state   *bool
	chunithm_main_ban_reason  *string
	chunithm_alias_ban_state  *bool
	chunithm_alias_ban_reason *string
	clearedFields             map[string]struct{}
	done                      bool
	oldValue                  func(context.Context) (*User, error)
	predicates                []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("users: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPlatform sets the "platform" field.
func (m *UserMutation) SetPlatform(s string) {
	m.platform = &s
}

// Platform returns the value of the "platform" field in the mutation.
func (m *UserMutation) Platform() (r string, exists bool) {
	v := m.platform
	if v == nil {
		return
	}
	return *v, true
}

// OldPlatform returns the old "platform" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPlatform(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPlatform is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPlatform requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPlatform: %w", err)
	}
	return oldValue.Platform, nil
}

// ResetPlatform resets all changes to the "platform" field.
func (m *UserMutation) ResetPlatform() {
	m.platform = nil
}

// SetUserID sets the "user_id" field.
func (m *UserMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *UserMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *UserMutation) ResetUserID() {
	m.user_id = nil
}

// SetBanState sets the "ban_state" field.
func (m *UserMutation) SetBanState(b bool) {
	m.ban_state = &b
}

// BanState returns the value of the "ban_state" field in the mutation.
func (m *UserMutation) BanState() (r bool, exists bool) {
	v := m.ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldBanState returns the old "ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBanState: %w", err)
	}
	return oldValue.BanState, nil
}

// ResetBanState resets all changes to the "ban_state" field.
func (m *UserMutation) ResetBanState() {
	m.ban_state = nil
}

// SetBanReason sets the "ban_reason" field.
func (m *UserMutation) SetBanReason(s string) {
	m.ban_reason = &s
}

// BanReason returns the value of the "ban_reason" field in the mutation.
func (m *UserMutation) BanReason() (r string, exists bool) {
	v := m.ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldBanReason returns the old "ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBanReason: %w", err)
	}
	return oldValue.BanReason, nil
}

// ClearBanReason clears the value of the "ban_reason" field.
func (m *UserMutation) ClearBanReason() {
	m.ban_reason = nil
	m.clearedFields[user.FieldBanReason] = struct{}{}
}

// BanReasonCleared returns if the "ban_reason" field was cleared in this mutation.
func (m *UserMutation) BanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldBanReason]
	return ok
}

// ResetBanReason resets all changes to the "ban_reason" field.
func (m *UserMutation) ResetBanReason() {
	m.ban_reason = nil
	delete(m.clearedFields, user.FieldBanReason)
}

// SetPjskBanState sets the "pjsk_ban_state" field.
func (m *UserMutation) SetPjskBanState(b bool) {
	m.pjsk_ban_state = &b
}

// PjskBanState returns the value of the "pjsk_ban_state" field in the mutation.
func (m *UserMutation) PjskBanState() (r bool, exists bool) {
	v := m.pjsk_ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskBanState returns the old "pjsk_ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskBanState: %w", err)
	}
	return oldValue.PjskBanState, nil
}

// ResetPjskBanState resets all changes to the "pjsk_ban_state" field.
func (m *UserMutation) ResetPjskBanState() {
	m.pjsk_ban_state = nil
}

// SetPjskBanReason sets the "pjsk_ban_reason" field.
func (m *UserMutation) SetPjskBanReason(s string) {
	m.pjsk_ban_reason = &s
}

// PjskBanReason returns the value of the "pjsk_ban_reason" field in the mutation.
func (m *UserMutation) PjskBanReason() (r string, exists bool) {
	v := m.pjsk_ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskBanReason returns the old "pjsk_ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskBanReason: %w", err)
	}
	return oldValue.PjskBanReason, nil
}

// ClearPjskBanReason clears the value of the "pjsk_ban_reason" field.
func (m *UserMutation) ClearPjskBanReason() {
	m.pjsk_ban_reason = nil
	m.clearedFields[user.FieldPjskBanReason] = struct{}{}
}

// PjskBanReasonCleared returns if the "pjsk_ban_reason" field was cleared in this mutation.
func (m *UserMutation) PjskBanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldPjskBanReason]
	return ok
}

// ResetPjskBanReason resets all changes to the "pjsk_ban_reason" field.
func (m *UserMutation) ResetPjskBanReason() {
	m.pjsk_ban_reason = nil
	delete(m.clearedFields, user.FieldPjskBanReason)
}

// SetChunithmBanState sets the "chunithm_ban_state" field.
func (m *UserMutation) SetChunithmBanState(b bool) {
	m.chunithm_ban_state = &b
}

// ChunithmBanState returns the value of the "chunithm_ban_state" field in the mutation.
func (m *UserMutation) ChunithmBanState() (r bool, exists bool) {
	v := m.chunithm_ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldChunithmBanState returns the old "chunithm_ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldChunithmBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChunithmBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChunithmBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChunithmBanState: %w", err)
	}
	return oldValue.ChunithmBanState, nil
}

// ResetChunithmBanState resets all changes to the "chunithm_ban_state" field.
func (m *UserMutation) ResetChunithmBanState() {
	m.chunithm_ban_state = nil
}

// SetChunithmBanReason sets the "chunithm_ban_reason" field.
func (m *UserMutation) SetChunithmBanReason(s string) {
	m.chunithm_ban_reason = &s
}

// ChunithmBanReason returns the value of the "chunithm_ban_reason" field in the mutation.
func (m *UserMutation) ChunithmBanReason() (r string, exists bool) {
	v := m.chunithm_ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldChunithmBanReason returns the old "chunithm_ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldChunithmBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChunithmBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChunithmBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChunithmBanReason: %w", err)
	}
	return oldValue.ChunithmBanReason, nil
}

// ClearChunithmBanReason clears the value of the "chunithm_ban_reason" field.
func (m *UserMutation) ClearChunithmBanReason() {
	m.chunithm_ban_reason = nil
	m.clearedFields[user.FieldChunithmBanReason] = struct{}{}
}

// ChunithmBanReasonCleared returns if the "chunithm_ban_reason" field was cleared in this mutation.
func (m *UserMutation) ChunithmBanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldChunithmBanReason]
	return ok
}

// ResetChunithmBanReason resets all changes to the "chunithm_ban_reason" field.
func (m *UserMutation) ResetChunithmBanReason() {
	m.chunithm_ban_reason = nil
	delete(m.clearedFields, user.FieldChunithmBanReason)
}

// SetPjskMainBanState sets the "pjsk_main_ban_state" field.
func (m *UserMutation) SetPjskMainBanState(b bool) {
	m.pjsk_main_ban_state = &b
}

// PjskMainBanState returns the value of the "pjsk_main_ban_state" field in the mutation.
func (m *UserMutation) PjskMainBanState() (r bool, exists bool) {
	v := m.pjsk_main_ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskMainBanState returns the old "pjsk_main_ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskMainBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskMainBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskMainBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskMainBanState: %w", err)
	}
	return oldValue.PjskMainBanState, nil
}

// ResetPjskMainBanState resets all changes to the "pjsk_main_ban_state" field.
func (m *UserMutation) ResetPjskMainBanState() {
	m.pjsk_main_ban_state = nil
}

// SetPjskMainBanReason sets the "pjsk_main_ban_reason" field.
func (m *UserMutation) SetPjskMainBanReason(s string) {
	m.pjsk_main_ban_reason = &s
}

// PjskMainBanReason returns the value of the "pjsk_main_ban_reason" field in the mutation.
func (m *UserMutation) PjskMainBanReason() (r string, exists bool) {
	v := m.pjsk_main_ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskMainBanReason returns the old "pjsk_main_ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskMainBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskMainBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskMainBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskMainBanReason: %w", err)
	}
	return oldValue.PjskMainBanReason, nil
}

// ClearPjskMainBanReason clears the value of the "pjsk_main_ban_reason" field.
func (m *UserMutation) ClearPjskMainBanReason() {
	m.pjsk_main_ban_reason = nil
	m.clearedFields[user.FieldPjskMainBanReason] = struct{}{}
}

// PjskMainBanReasonCleared returns if the "pjsk_main_ban_reason" field was cleared in this mutation.
func (m *UserMutation) PjskMainBanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldPjskMainBanReason]
	return ok
}

// ResetPjskMainBanReason resets all changes to the "pjsk_main_ban_reason" field.
func (m *UserMutation) ResetPjskMainBanReason() {
	m.pjsk_main_ban_reason = nil
	delete(m.clearedFields, user.FieldPjskMainBanReason)
}

// SetPjskRankingBanState sets the "pjsk_ranking_ban_state" field.
func (m *UserMutation) SetPjskRankingBanState(b bool) {
	m.pjsk_ranking_ban_state = &b
}

// PjskRankingBanState returns the value of the "pjsk_ranking_ban_state" field in the mutation.
func (m *UserMutation) PjskRankingBanState() (r bool, exists bool) {
	v := m.pjsk_ranking_ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskRankingBanState returns the old "pjsk_ranking_ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskRankingBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskRankingBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskRankingBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskRankingBanState: %w", err)
	}
	return oldValue.PjskRankingBanState, nil
}

// ResetPjskRankingBanState resets all changes to the "pjsk_ranking_ban_state" field.
func (m *UserMutation) ResetPjskRankingBanState() {
	m.pjsk_ranking_ban_state = nil
}

// SetPjskRankingBanReason sets the "pjsk_ranking_ban_reason" field.
func (m *UserMutation) SetPjskRankingBanReason(s string) {
	m.pjsk_ranking_ban_reason = &s
}

// PjskRankingBanReason returns the value of the "pjsk_ranking_ban_reason" field in the mutation.
func (m *UserMutation) PjskRankingBanReason() (r string, exists bool) {
	v := m.pjsk_ranking_ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskRankingBanReason returns the old "pjsk_ranking_ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskRankingBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskRankingBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskRankingBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskRankingBanReason: %w", err)
	}
	return oldValue.PjskRankingBanReason, nil
}

// ClearPjskRankingBanReason clears the value of the "pjsk_ranking_ban_reason" field.
func (m *UserMutation) ClearPjskRankingBanReason() {
	m.pjsk_ranking_ban_reason = nil
	m.clearedFields[user.FieldPjskRankingBanReason] = struct{}{}
}

// PjskRankingBanReasonCleared returns if the "pjsk_ranking_ban_reason" field was cleared in this mutation.
func (m *UserMutation) PjskRankingBanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldPjskRankingBanReason]
	return ok
}

// ResetPjskRankingBanReason resets all changes to the "pjsk_ranking_ban_reason" field.
func (m *UserMutation) ResetPjskRankingBanReason() {
	m.pjsk_ranking_ban_reason = nil
	delete(m.clearedFields, user.FieldPjskRankingBanReason)
}

// SetPjskAliasBanState sets the "pjsk_alias_ban_state" field.
func (m *UserMutation) SetPjskAliasBanState(b bool) {
	m.pjsk_alias_ban_state = &b
}

// PjskAliasBanState returns the value of the "pjsk_alias_ban_state" field in the mutation.
func (m *UserMutation) PjskAliasBanState() (r bool, exists bool) {
	v := m.pjsk_alias_ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskAliasBanState returns the old "pjsk_alias_ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskAliasBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskAliasBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskAliasBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskAliasBanState: %w", err)
	}
	return oldValue.PjskAliasBanState, nil
}

// ResetPjskAliasBanState resets all changes to the "pjsk_alias_ban_state" field.
func (m *UserMutation) ResetPjskAliasBanState() {
	m.pjsk_alias_ban_state = nil
}

// SetPjskAliasBanReason sets the "pjsk_alias_ban_reason" field.
func (m *UserMutation) SetPjskAliasBanReason(s string) {
	m.pjsk_alias_ban_reason = &s
}

// PjskAliasBanReason returns the value of the "pjsk_alias_ban_reason" field in the mutation.
func (m *UserMutation) PjskAliasBanReason() (r string, exists bool) {
	v := m.pjsk_alias_ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskAliasBanReason returns the old "pjsk_alias_ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskAliasBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskAliasBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskAliasBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskAliasBanReason: %w", err)
	}
	return oldValue.PjskAliasBanReason, nil
}

// ClearPjskAliasBanReason clears the value of the "pjsk_alias_ban_reason" field.
func (m *UserMutation) ClearPjskAliasBanReason() {
	m.pjsk_alias_ban_reason = nil
	m.clearedFields[user.FieldPjskAliasBanReason] = struct{}{}
}

// PjskAliasBanReasonCleared returns if the "pjsk_alias_ban_reason" field was cleared in this mutation.
func (m *UserMutation) PjskAliasBanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldPjskAliasBanReason]
	return ok
}

// ResetPjskAliasBanReason resets all changes to the "pjsk_alias_ban_reason" field.
func (m *UserMutation) ResetPjskAliasBanReason() {
	m.pjsk_alias_ban_reason = nil
	delete(m.clearedFields, user.FieldPjskAliasBanReason)
}

// SetPjskMysekaiBanState sets the "pjsk_mysekai_ban_state" field.
func (m *UserMutation) SetPjskMysekaiBanState(b bool) {
	m.pjsk_mysekai_ban_state = &b
}

// PjskMysekaiBanState returns the value of the "pjsk_mysekai_ban_state" field in the mutation.
func (m *UserMutation) PjskMysekaiBanState() (r bool, exists bool) {
	v := m.pjsk_mysekai_ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskMysekaiBanState returns the old "pjsk_mysekai_ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskMysekaiBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskMysekaiBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskMysekaiBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskMysekaiBanState: %w", err)
	}
	return oldValue.PjskMysekaiBanState, nil
}

// ResetPjskMysekaiBanState resets all changes to the "pjsk_mysekai_ban_state" field.
func (m *UserMutation) ResetPjskMysekaiBanState() {
	m.pjsk_mysekai_ban_state = nil
}

// SetPjskMysekaiBanReason sets the "pjsk_mysekai_ban_reason" field.
func (m *UserMutation) SetPjskMysekaiBanReason(s string) {
	m.pjsk_mysekai_ban_reason = &s
}

// PjskMysekaiBanReason returns the value of the "pjsk_mysekai_ban_reason" field in the mutation.
func (m *UserMutation) PjskMysekaiBanReason() (r string, exists bool) {
	v := m.pjsk_mysekai_ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldPjskMysekaiBanReason returns the old "pjsk_mysekai_ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPjskMysekaiBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPjskMysekaiBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPjskMysekaiBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPjskMysekaiBanReason: %w", err)
	}
	return oldValue.PjskMysekaiBanReason, nil
}

// ClearPjskMysekaiBanReason clears the value of the "pjsk_mysekai_ban_reason" field.
func (m *UserMutation) ClearPjskMysekaiBanReason() {
	m.pjsk_mysekai_ban_reason = nil
	m.clearedFields[user.FieldPjskMysekaiBanReason] = struct{}{}
}

// PjskMysekaiBanReasonCleared returns if the "pjsk_mysekai_ban_reason" field was cleared in this mutation.
func (m *UserMutation) PjskMysekaiBanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldPjskMysekaiBanReason]
	return ok
}

// ResetPjskMysekaiBanReason resets all changes to the "pjsk_mysekai_ban_reason" field.
func (m *UserMutation) ResetPjskMysekaiBanReason() {
	m.pjsk_mysekai_ban_reason = nil
	delete(m.clearedFields, user.FieldPjskMysekaiBanReason)
}

// SetChunithmMainBanState sets the "chunithm_main_ban_state" field.
func (m *UserMutation) SetChunithmMainBanState(b bool) {
	m.chunithm_main_ban_state = &b
}

// ChunithmMainBanState returns the value of the "chunithm_main_ban_state" field in the mutation.
func (m *UserMutation) ChunithmMainBanState() (r bool, exists bool) {
	v := m.chunithm_main_ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldChunithmMainBanState returns the old "chunithm_main_ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldChunithmMainBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChunithmMainBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChunithmMainBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChunithmMainBanState: %w", err)
	}
	return oldValue.ChunithmMainBanState, nil
}

// ResetChunithmMainBanState resets all changes to the "chunithm_main_ban_state" field.
func (m *UserMutation) ResetChunithmMainBanState() {
	m.chunithm_main_ban_state = nil
}

// SetChunithmMainBanReason sets the "chunithm_main_ban_reason" field.
func (m *UserMutation) SetChunithmMainBanReason(s string) {
	m.chunithm_main_ban_reason = &s
}

// ChunithmMainBanReason returns the value of the "chunithm_main_ban_reason" field in the mutation.
func (m *UserMutation) ChunithmMainBanReason() (r string, exists bool) {
	v := m.chunithm_main_ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldChunithmMainBanReason returns the old "chunithm_main_ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldChunithmMainBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChunithmMainBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChunithmMainBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChunithmMainBanReason: %w", err)
	}
	return oldValue.ChunithmMainBanReason, nil
}

// ClearChunithmMainBanReason clears the value of the "chunithm_main_ban_reason" field.
func (m *UserMutation) ClearChunithmMainBanReason() {
	m.chunithm_main_ban_reason = nil
	m.clearedFields[user.FieldChunithmMainBanReason] = struct{}{}
}

// ChunithmMainBanReasonCleared returns if the "chunithm_main_ban_reason" field was cleared in this mutation.
func (m *UserMutation) ChunithmMainBanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldChunithmMainBanReason]
	return ok
}

// ResetChunithmMainBanReason resets all changes to the "chunithm_main_ban_reason" field.
func (m *UserMutation) ResetChunithmMainBanReason() {
	m.chunithm_main_ban_reason = nil
	delete(m.clearedFields, user.FieldChunithmMainBanReason)
}

// SetChunithmAliasBanState sets the "chunithm_alias_ban_state" field.
func (m *UserMutation) SetChunithmAliasBanState(b bool) {
	m.chunithm_alias_ban_state = &b
}

// ChunithmAliasBanState returns the value of the "chunithm_alias_ban_state" field in the mutation.
func (m *UserMutation) ChunithmAliasBanState() (r bool, exists bool) {
	v := m.chunithm_alias_ban_state
	if v == nil {
		return
	}
	return *v, true
}

// OldChunithmAliasBanState returns the old "chunithm_alias_ban_state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldChunithmAliasBanState(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChunithmAliasBanState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChunithmAliasBanState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChunithmAliasBanState: %w", err)
	}
	return oldValue.ChunithmAliasBanState, nil
}

// ResetChunithmAliasBanState resets all changes to the "chunithm_alias_ban_state" field.
func (m *UserMutation) ResetChunithmAliasBanState() {
	m.chunithm_alias_ban_state = nil
}

// SetChunithmAliasBanReason sets the "chunithm_alias_ban_reason" field.
func (m *UserMutation) SetChunithmAliasBanReason(s string) {
	m.chunithm_alias_ban_reason = &s
}

// ChunithmAliasBanReason returns the value of the "chunithm_alias_ban_reason" field in the mutation.
func (m *UserMutation) ChunithmAliasBanReason() (r string, exists bool) {
	v := m.chunithm_alias_ban_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldChunithmAliasBanReason returns the old "chunithm_alias_ban_reason" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldChunithmAliasBanReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChunithmAliasBanReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChunithmAliasBanReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChunithmAliasBanReason: %w", err)
	}
	return oldValue.ChunithmAliasBanReason, nil
}

// ClearChunithmAliasBanReason clears the value of the "chunithm_alias_ban_reason" field.
func (m *UserMutation) ClearChunithmAliasBanReason() {
	m.chunithm_alias_ban_reason = nil
	m.clearedFields[user.FieldChunithmAliasBanReason] = struct{}{}
}

// ChunithmAliasBanReasonCleared returns if the "chunithm_alias_ban_reason" field was cleared in this mutation.
func (m *UserMutation) ChunithmAliasBanReasonCleared() bool {
	_, ok := m.clearedFields[user.FieldChunithmAliasBanReason]
	return ok
}

// ResetChunithmAliasBanReason resets all changes to the "chunithm_alias_ban_reason" field.
func (m *UserMutation) ResetChunithmAliasBanReason() {
	m.chunithm_alias_ban_reason = nil
	delete(m.clearedFields, user.FieldChunithmAliasBanReason)
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 20)
	if m.platform != nil {
		fields = append(fields, user.FieldPlatform)
	}
	if m.user_id != nil {
		fields = append(fields, user.FieldUserID)
	}
	if m.ban_state != nil {
		fields = append(fields, user.FieldBanState)
	}
	if m.ban_reason != nil {
		fields = append(fields, user.FieldBanReason)
	}
	if m.pjsk_ban_state != nil {
		fields = append(fields, user.FieldPjskBanState)
	}
	if m.pjsk_ban_reason != nil {
		fields = append(fields, user.FieldPjskBanReason)
	}
	if m.chunithm_ban_state != nil {
		fields = append(fields, user.FieldChunithmBanState)
	}
	if m.chunithm_ban_reason != nil {
		fields = append(fields, user.FieldChunithmBanReason)
	}
	if m.pjsk_main_ban_state != nil {
		fields = append(fields, user.FieldPjskMainBanState)
	}
	if m.pjsk_main_ban_reason != nil {
		fields = append(fields, user.FieldPjskMainBanReason)
	}
	if m.pjsk_ranking_ban_state != nil {
		fields = append(fields, user.FieldPjskRankingBanState)
	}
	if m.pjsk_ranking_ban_reason != nil {
		fields = append(fields, user.FieldPjskRankingBanReason)
	}
	if m.pjsk_alias_ban_state != nil {
		fields = append(fields, user.FieldPjskAliasBanState)
	}
	if m.pjsk_alias_ban_reason != nil {
		fields = append(fields, user.FieldPjskAliasBanReason)
	}
	if m.pjsk_mysekai_ban_state != nil {
		fields = append(fields, user.FieldPjskMysekaiBanState)
	}
	if m.pjsk_mysekai_ban_reason != nil {
		fields = append(fields, user.FieldPjskMysekaiBanReason)
	}
	if m.chunithm_main_ban_state != nil {
		fields = append(fields, user.FieldChunithmMainBanState)
	}
	if m.chunithm_main_ban_reason != nil {
		fields = append(fields, user.FieldChunithmMainBanReason)
	}
	if m.chunithm_alias_ban_state != nil {
		fields = append(fields, user.FieldChunithmAliasBanState)
	}
	if m.chunithm_alias_ban_reason != nil {
		fields = append(fields, user.FieldChunithmAliasBanReason)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldPlatform:
		return m.Platform()
	case user.FieldUserID:
		return m.UserID()
	case user.FieldBanState:
		return m.BanState()
	case user.FieldBanReason:
		return m.BanReason()
	case user.FieldPjskBanState:
		return m.PjskBanState()
	case user.FieldPjskBanReason:
		return m.PjskBanReason()
	case user.FieldChunithmBanState:
		return m.ChunithmBanState()
	case user.FieldChunithmBanReason:
		return m.ChunithmBanReason()
	case user.FieldPjskMainBanState:
		return m.PjskMainBanState()
	case user.FieldPjskMainBanReason:
		return m.PjskMainBanReason()
	case user.FieldPjskRankingBanState:
		return m.PjskRankingBanState()
	case user.FieldPjskRankingBanReason:
		return m.PjskRankingBanReason()
	case user.FieldPjskAliasBanState:
		return m.PjskAliasBanState()
	case user.FieldPjskAliasBanReason:
		return m.PjskAliasBanReason()
	case user.FieldPjskMysekaiBanState:
		return m.PjskMysekaiBanState()
	case user.FieldPjskMysekaiBanReason:
		return m.PjskMysekaiBanReason()
	case user.FieldChunithmMainBanState:
		return m.ChunithmMainBanState()
	case user.FieldChunithmMainBanReason:
		return m.ChunithmMainBanReason()
	case user.FieldChunithmAliasBanState:
		return m.ChunithmAliasBanState()
	case user.FieldChunithmAliasBanReason:
		return m.ChunithmAliasBanReason()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldPlatform:
		return m.OldPlatform(ctx)
	case user.FieldUserID:
		return m.OldUserID(ctx)
	case user.FieldBanState:
		return m.OldBanState(ctx)
	case user.FieldBanReason:
		return m.OldBanReason(ctx)
	case user.FieldPjskBanState:
		return m.OldPjskBanState(ctx)
	case user.FieldPjskBanReason:
		return m.OldPjskBanReason(ctx)
	case user.FieldChunithmBanState:
		return m.OldChunithmBanState(ctx)
	case user.FieldChunithmBanReason:
		return m.OldChunithmBanReason(ctx)
	case user.FieldPjskMainBanState:
		return m.OldPjskMainBanState(ctx)
	case user.FieldPjskMainBanReason:
		return m.OldPjskMainBanReason(ctx)
	case user.FieldPjskRankingBanState:
		return m.OldPjskRankingBanState(ctx)
	case user.FieldPjskRankingBanReason:
		return m.OldPjskRankingBanReason(ctx)
	case user.FieldPjskAliasBanState:
		return m.OldPjskAliasBanState(ctx)
	case user.FieldPjskAliasBanReason:
		return m.OldPjskAliasBanReason(ctx)
	case user.FieldPjskMysekaiBanState:
		return m.OldPjskMysekaiBanState(ctx)
	case user.FieldPjskMysekaiBanReason:
		return m.OldPjskMysekaiBanReason(ctx)
	case user.FieldChunithmMainBanState:
		return m.OldChunithmMainBanState(ctx)
	case user.FieldChunithmMainBanReason:
		return m.OldChunithmMainBanReason(ctx)
	case user.FieldChunithmAliasBanState:
		return m.OldChunithmAliasBanState(ctx)
	case user.FieldChunithmAliasBanReason:
		return m.OldChunithmAliasBanReason(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldPlatform:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPlatform(v)
		return nil
	case user.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case user.FieldBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBanState(v)
		return nil
	case user.FieldBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBanReason(v)
		return nil
	case user.FieldPjskBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskBanState(v)
		return nil
	case user.FieldPjskBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskBanReason(v)
		return nil
	case user.FieldChunithmBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChunithmBanState(v)
		return nil
	case user.FieldChunithmBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChunithmBanReason(v)
		return nil
	case user.FieldPjskMainBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskMainBanState(v)
		return nil
	case user.FieldPjskMainBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskMainBanReason(v)
		return nil
	case user.FieldPjskRankingBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskRankingBanState(v)
		return nil
	case user.FieldPjskRankingBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskRankingBanReason(v)
		return nil
	case user.FieldPjskAliasBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskAliasBanState(v)
		return nil
	case user.FieldPjskAliasBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskAliasBanReason(v)
		return nil
	case user.FieldPjskMysekaiBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskMysekaiBanState(v)
		return nil
	case user.FieldPjskMysekaiBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPjskMysekaiBanReason(v)
		return nil
	case user.FieldChunithmMainBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChunithmMainBanState(v)
		return nil
	case user.FieldChunithmMainBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChunithmMainBanReason(v)
		return nil
	case user.FieldChunithmAliasBanState:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChunithmAliasBanState(v)
		return nil
	case user.FieldChunithmAliasBanReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChunithmAliasBanReason(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(user.FieldBanReason) {
		fields = append(fields, user.FieldBanReason)
	}
	if m.FieldCleared(user.FieldPjskBanReason) {
		fields = append(fields, user.FieldPjskBanReason)
	}
	if m.FieldCleared(user.FieldChunithmBanReason) {
		fields = append(fields, user.FieldChunithmBanReason)
	}
	if m.FieldCleared(user.FieldPjskMainBanReason) {
		fields = append(fields, user.FieldPjskMainBanReason)
	}
	if m.FieldCleared(user.FieldPjskRankingBanReason) {
		fields = append(fields, user.FieldPjskRankingBanReason)
	}
	if m.FieldCleared(user.FieldPjskAliasBanReason) {
		fields = append(fields, user.FieldPjskAliasBanReason)
	}
	if m.FieldCleared(user.FieldPjskMysekaiBanReason) {
		fields = append(fields, user.FieldPjskMysekaiBanReason)
	}
	if m.FieldCleared(user.FieldChunithmMainBanReason) {
		fields = append(fields, user.FieldChunithmMainBanReason)
	}
	if m.FieldCleared(user.FieldChunithmAliasBanReason) {
		fields = append(fields, user.FieldChunithmAliasBanReason)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	switch name {
	case user.FieldBanReason:
		m.ClearBanReason()
		return nil
	case user.FieldPjskBanReason:
		m.ClearPjskBanReason()
		return nil
	case user.FieldChunithmBanReason:
		m.ClearChunithmBanReason()
		return nil
	case user.FieldPjskMainBanReason:
		m.ClearPjskMainBanReason()
		return nil
	case user.FieldPjskRankingBanReason:
		m.ClearPjskRankingBanReason()
		return nil
	case user.FieldPjskAliasBanReason:
		m.ClearPjskAliasBanReason()
		return nil
	case user.FieldPjskMysekaiBanReason:
		m.ClearPjskMysekaiBanReason()
		return nil
	case user.FieldChunithmMainBanReason:
		m.ClearChunithmMainBanReason()
		return nil
	case user.FieldChunithmAliasBanReason:
		m.ClearChunithmAliasBanReason()
		return nil
	}
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldPlatform:
		m.ResetPlatform()
		return nil
	case user.FieldUserID:
		m.ResetUserID()
		return nil
	case user.FieldBanState:
		m.ResetBanState()
		return nil
	case user.FieldBanReason:
		m.ResetBanReason()
		return nil
	case user.FieldPjskBanState:
		m.ResetPjskBanState()
		return nil
	case user.FieldPjskBanReason:
		m.ResetPjskBanReason()
		return nil
	case user.FieldChunithmBanState:
		m.ResetChunithmBanState()
		return nil
	case user.FieldChunithmBanReason:
		m.ResetChunithmBanReason()
		return nil
	case user.FieldPjskMainBanState:
		m.ResetPjskMainBanState()
		return nil
	case user.FieldPjskMainBanReason:
		m.ResetPjskMainBanReason()
		return nil
	case user.FieldPjskRankingBanState:
		m.ResetPjskRankingBanState()
		return nil
	case user.FieldPjskRankingBanReason:
		m.ResetPjskRankingBanReason()
		return nil
	case user.FieldPjskAliasBanState:
		m.ResetPjskAliasBanState()
		return nil
	case user.FieldPjskAliasBanReason:
		m.ResetPjskAliasBanReason()
		return nil
	case user.FieldPjskMysekaiBanState:
		m.ResetPjskMysekaiBanState()
		return nil
	case user.FieldPjskMysekaiBanReason:
		m.ResetPjskMysekaiBanReason()
		return nil
	case user.FieldChunithmMainBanState:
		m.ResetChunithmMainBanState()
		return nil
	case user.FieldChunithmMainBanReason:
		m.ResetChunithmMainBanReason()
		return nil
	case user.FieldChunithmAliasBanState:
		m.ResetChunithmAliasBanState()
		return nil
	case user.FieldChunithmAliasBanReason:
		m.ResetChunithmAliasBanReason()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown User edge %s", name)
}
