// Code generated by ent, DO NOT EDIT.

package users

import (
	"context"
	"errors"
	"fmt"
	"haruki-database/database/schema/users/predicate"
	"haruki-database/database/schema/users/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UserUpdate) SetPlatform(v string) *UserUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePlatform(v *string) *UserUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserUpdate) SetUserID(v string) *UserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserID(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBanState sets the "ban_state" field.
func (_u *UserUpdate) SetBanState(v bool) *UserUpdate {
	_u.mutation.SetBanState(v)
	return _u
}

// SetNillableBanState sets the "ban_state" field if the given value is not nil.
func (_u *UserUpdate) SetNillableBanState(v *bool) *UserUpdate {
	if v != nil {
		_u.SetBanState(*v)
	}
	return _u
}

// SetBanReason sets the "ban_reason" field.
func (_u *UserUpdate) SetBanReason(v string) *UserUpdate {
	_u.mutation.SetBanReason(v)
	return _u
}

// SetNillableBanReason sets the "ban_reason" field if the given value is not nil.
func (_u *UserUpdate) SetNillableBanReason(v *string) *UserUpdate {
	if v != nil {
		_u.SetBanReason(*v)
	}
	return _u
}

// ClearBanReason clears the value of the "ban_reason" field.
func (_u *UserUpdate) ClearBanReason() *UserUpdate {
	_u.mutation.ClearBanReason()
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := user.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`users: validator failed for field "User.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := user.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`users: validator failed for field "User.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BanReason(); ok {
		if err := user.BanReasonValidator(v); err != nil {
			return &ValidationError{Name: "ban_reason", err: fmt.Errorf(`users: validator failed for field "User.ban_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(user.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(user.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BanState(); ok {
		_spec.SetField(user.FieldBanState, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BanReason(); ok {
		_spec.SetField(user.FieldBanReason, field.TypeString, value)
	}
	if _u.mutation.BanReasonCleared() {
		_spec.ClearField(user.FieldBanReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetPlatform sets the "platform" field.
func (_u *UserUpdateOne) SetPlatform(v string) *UserUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePlatform(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserUpdateOne) SetUserID(v string) *UserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBanState sets the "ban_state" field.
func (_u *UserUpdateOne) SetBanState(v bool) *UserUpdateOne {
	_u.mutation.SetBanState(v)
	return _u
}

// SetNillableBanState sets the "ban_state" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableBanState(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetBanState(*v)
	}
	return _u
}

// SetBanReason sets the "ban_reason" field.
func (_u *UserUpdateOne) SetBanReason(v string) *UserUpdateOne {
	_u.mutation.SetBanReason(v)
	return _u
}

// SetNillableBanReason sets the "ban_reason" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableBanReason(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetBanReason(*v)
	}
	return _u
}

// ClearBanReason clears the value of the "ban_reason" field.
func (_u *UserUpdateOne) ClearBanReason() *UserUpdateOne {
	_u.mutation.ClearBanReason()
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := user.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`users: validator failed for field "User.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := user.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`users: validator failed for field "User.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BanReason(); ok {
		if err := user.BanReasonValidator(v); err != nil {
			return &ValidationError{Name: "ban_reason", err: fmt.Errorf(`users: validator failed for field "User.ban_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`users: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("users: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(user.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(user.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BanState(); ok {
		_spec.SetField(user.FieldBanState, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BanReason(); ok {
		_spec.SetField(user.FieldBanReason, field.TypeString, value)
	}
	if _u.mutation.BanReasonCleared() {
		_spec.ClearField(user.FieldBanReason, field.TypeString)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
