// Code generated by ent, DO NOT EDIT.

package maindb

import (
	"context"
	"haruki-database/database/schema/chunithm/maindb/chunithmmusicalias"
	"haruki-database/database/schema/chunithm/maindb/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChunithmMusicAliasDelete is the builder for deleting a ChunithmMusicAlias entity.
type ChunithmMusicAliasDelete struct {
	config
	hooks    []Hook
	mutation *ChunithmMusicAliasMutation
}

// Where appends a list predicates to the ChunithmMusicAliasDelete builder.
func (_d *ChunithmMusicAliasDelete) Where(ps ...predicate.ChunithmMusicAlias) *ChunithmMusicAliasDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChunithmMusicAliasDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChunithmMusicAliasDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChunithmMusicAliasDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chunithmmusicalias.Table, sqlgraph.NewFieldSpec(chunithmmusicalias.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChunithmMusicAliasDeleteOne is the builder for deleting a single ChunithmMusicAlias entity.
type ChunithmMusicAliasDeleteOne struct {
	_d *ChunithmMusicAliasDelete
}

// Where appends a list predicates to the ChunithmMusicAliasDelete builder.
func (_d *ChunithmMusicAliasDeleteOne) Where(ps ...predicate.ChunithmMusicAlias) *ChunithmMusicAliasDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChunithmMusicAliasDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chunithmmusicalias.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChunithmMusicAliasDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
