// Code generated by ent, DO NOT EDIT.

package maindb

import (
	"context"
	"errors"
	"fmt"
	"haruki-database/database/schema/chunithm/maindb/chunithmdefaultserver"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChunithmDefaultServerCreate is the builder for creating a ChunithmDefaultServer entity.
type ChunithmDefaultServerCreate struct {
	config
	mutation *ChunithmDefaultServerMutation
	hooks    []Hook
}

// SetHarukiUserID sets the "haruki_user_id" field.
func (_c *ChunithmDefaultServerCreate) SetHarukiUserID(v int) *ChunithmDefaultServerCreate {
	_c.mutation.SetHarukiUserID(v)
	return _c
}

// SetServer sets the "server" field.
func (_c *ChunithmDefaultServerCreate) SetServer(v string) *ChunithmDefaultServerCreate {
	_c.mutation.SetServer(v)
	return _c
}

// Mutation returns the ChunithmDefaultServerMutation object of the builder.
func (_c *ChunithmDefaultServerCreate) Mutation() *ChunithmDefaultServerMutation {
	return _c.mutation
}

// Save creates the ChunithmDefaultServer in the database.
func (_c *ChunithmDefaultServerCreate) Save(ctx context.Context) (*ChunithmDefaultServer, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChunithmDefaultServerCreate) SaveX(ctx context.Context) *ChunithmDefaultServer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunithmDefaultServerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunithmDefaultServerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChunithmDefaultServerCreate) check() error {
	if _, ok := _c.mutation.HarukiUserID(); !ok {
		return &ValidationError{Name: "haruki_user_id", err: errors.New(`maindb: missing required field "ChunithmDefaultServer.haruki_user_id"`)}
	}
	if _, ok := _c.mutation.Server(); !ok {
		return &ValidationError{Name: "server", err: errors.New(`maindb: missing required field "ChunithmDefaultServer.server"`)}
	}
	if v, ok := _c.mutation.Server(); ok {
		if err := chunithmdefaultserver.ServerValidator(v); err != nil {
			return &ValidationError{Name: "server", err: fmt.Errorf(`maindb: validator failed for field "ChunithmDefaultServer.server": %w`, err)}
		}
	}
	return nil
}

func (_c *ChunithmDefaultServerCreate) sqlSave(ctx context.Context) (*ChunithmDefaultServer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChunithmDefaultServerCreate) createSpec() (*ChunithmDefaultServer, *sqlgraph.CreateSpec) {
	var (
		_node = &ChunithmDefaultServer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chunithmdefaultserver.Table, sqlgraph.NewFieldSpec(chunithmdefaultserver.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.HarukiUserID(); ok {
		_spec.SetField(chunithmdefaultserver.FieldHarukiUserID, field.TypeInt, value)
		_node.HarukiUserID = value
	}
	if value, ok := _c.mutation.Server(); ok {
		_spec.SetField(chunithmdefaultserver.FieldServer, field.TypeString, value)
		_node.Server = value
	}
	return _node, _spec
}

// ChunithmDefaultServerCreateBulk is the builder for creating many ChunithmDefaultServer entities in bulk.
type ChunithmDefaultServerCreateBulk struct {
	config
	err      error
	builders []*ChunithmDefaultServerCreate
}

// Save creates the ChunithmDefaultServer entities in the database.
func (_c *ChunithmDefaultServerCreateBulk) Save(ctx context.Context) ([]*ChunithmDefaultServer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChunithmDefaultServer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChunithmDefaultServerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChunithmDefaultServerCreateBulk) SaveX(ctx context.Context) []*ChunithmDefaultServer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunithmDefaultServerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunithmDefaultServerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
