// Code generated by ent, DO NOT EDIT.

package maindb

import (
	"context"
	"fmt"
	"haruki-database/database/schema/chunithm/maindb/chunithmmusicalias"
	"haruki-database/database/schema/chunithm/maindb/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChunithmMusicAliasQuery is the builder for querying ChunithmMusicAlias entities.
type ChunithmMusicAliasQuery struct {
	config
	ctx        *QueryContext
	order      []chunithmmusicalias.OrderOption
	inters     []Interceptor
	predicates []predicate.ChunithmMusicAlias
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChunithmMusicAliasQuery builder.
func (_q *ChunithmMusicAliasQuery) Where(ps ...predicate.ChunithmMusicAlias) *ChunithmMusicAliasQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChunithmMusicAliasQuery) Limit(limit int) *ChunithmMusicAliasQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChunithmMusicAliasQuery) Offset(offset int) *ChunithmMusicAliasQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChunithmMusicAliasQuery) Unique(unique bool) *ChunithmMusicAliasQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChunithmMusicAliasQuery) Order(o ...chunithmmusicalias.OrderOption) *ChunithmMusicAliasQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first ChunithmMusicAlias entity from the query.
// Returns a *NotFoundError when no ChunithmMusicAlias was found.
func (_q *ChunithmMusicAliasQuery) First(ctx context.Context) (*ChunithmMusicAlias, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chunithmmusicalias.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChunithmMusicAliasQuery) FirstX(ctx context.Context) *ChunithmMusicAlias {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChunithmMusicAlias ID from the query.
// Returns a *NotFoundError when no ChunithmMusicAlias ID was found.
func (_q *ChunithmMusicAliasQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chunithmmusicalias.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChunithmMusicAliasQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChunithmMusicAlias entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChunithmMusicAlias entity is found.
// Returns a *NotFoundError when no ChunithmMusicAlias entities are found.
func (_q *ChunithmMusicAliasQuery) Only(ctx context.Context) (*ChunithmMusicAlias, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chunithmmusicalias.Label}
	default:
		return nil, &NotSingularError{chunithmmusicalias.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChunithmMusicAliasQuery) OnlyX(ctx context.Context) *ChunithmMusicAlias {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChunithmMusicAlias ID in the query.
// Returns a *NotSingularError when more than one ChunithmMusicAlias ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChunithmMusicAliasQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chunithmmusicalias.Label}
	default:
		err = &NotSingularError{chunithmmusicalias.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChunithmMusicAliasQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChunithmMusicAliasSlice.
func (_q *ChunithmMusicAliasQuery) All(ctx context.Context) ([]*ChunithmMusicAlias, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChunithmMusicAlias, *ChunithmMusicAliasQuery]()
	return withInterceptors[[]*ChunithmMusicAlias](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChunithmMusicAliasQuery) AllX(ctx context.Context) []*ChunithmMusicAlias {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChunithmMusicAlias IDs.
func (_q *ChunithmMusicAliasQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(chunithmmusicalias.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChunithmMusicAliasQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChunithmMusicAliasQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChunithmMusicAliasQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChunithmMusicAliasQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChunithmMusicAliasQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("maindb: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChunithmMusicAliasQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChunithmMusicAliasQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChunithmMusicAliasQuery) Clone() *ChunithmMusicAliasQuery {
	if _q == nil {
		return nil
	}
	return &ChunithmMusicAliasQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]chunithmmusicalias.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ChunithmMusicAlias{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MusicID int `json:"music_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChunithmMusicAlias.Query().
//		GroupBy(chunithmmusicalias.FieldMusicID).
//		Aggregate(maindb.Count()).
//		Scan(ctx, &v)
func (_q *ChunithmMusicAliasQuery) GroupBy(field string, fields ...string) *ChunithmMusicAliasGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChunithmMusicAliasGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chunithmmusicalias.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MusicID int `json:"music_id,omitempty"`
//	}
//
//	client.ChunithmMusicAlias.Query().
//		Select(chunithmmusicalias.FieldMusicID).
//		Scan(ctx, &v)
func (_q *ChunithmMusicAliasQuery) Select(fields ...string) *ChunithmMusicAliasSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChunithmMusicAliasSelect{ChunithmMusicAliasQuery: _q}
	sbuild.label = chunithmmusicalias.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChunithmMusicAliasSelect configured with the given aggregations.
func (_q *ChunithmMusicAliasQuery) Aggregate(fns ...AggregateFunc) *ChunithmMusicAliasSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChunithmMusicAliasQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("maindb: uninitialized interceptor (forgotten import maindb/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chunithmmusicalias.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("maindb: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChunithmMusicAliasQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChunithmMusicAlias, error) {
	var (
		nodes = []*ChunithmMusicAlias{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChunithmMusicAlias).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChunithmMusicAlias{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *ChunithmMusicAliasQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChunithmMusicAliasQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chunithmmusicalias.Table, chunithmmusicalias.Columns, sqlgraph.NewFieldSpec(chunithmmusicalias.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chunithmmusicalias.FieldID)
		for i := range fields {
			if fields[i] != chunithmmusicalias.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChunithmMusicAliasQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chunithmmusicalias.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chunithmmusicalias.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChunithmMusicAliasGroupBy is the group-by builder for ChunithmMusicAlias entities.
type ChunithmMusicAliasGroupBy struct {
	selector
	build *ChunithmMusicAliasQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChunithmMusicAliasGroupBy) Aggregate(fns ...AggregateFunc) *ChunithmMusicAliasGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChunithmMusicAliasGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChunithmMusicAliasQuery, *ChunithmMusicAliasGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChunithmMusicAliasGroupBy) sqlScan(ctx context.Context, root *ChunithmMusicAliasQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChunithmMusicAliasSelect is the builder for selecting fields of ChunithmMusicAlias entities.
type ChunithmMusicAliasSelect struct {
	*ChunithmMusicAliasQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChunithmMusicAliasSelect) Aggregate(fns ...AggregateFunc) *ChunithmMusicAliasSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChunithmMusicAliasSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChunithmMusicAliasQuery, *ChunithmMusicAliasSelect](ctx, _s.ChunithmMusicAliasQuery, _s, _s.inters, v)
}

func (_s *ChunithmMusicAliasSelect) sqlScan(ctx context.Context, root *ChunithmMusicAliasQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
