// Code generated by ent, DO NOT EDIT.

package userpreference

import (
	"haruki-database/database/schema/pjsk/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldID, id))
}

// HarukiUserID applies equality check predicate on the "haruki_user_id" field. It's identical to HarukiUserIDEQ.
func HarukiUserID(v int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldHarukiUserID, v))
}

// Option applies equality check predicate on the "option" field. It's identical to OptionEQ.
func Option(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldOption, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldValue, v))
}

// HarukiUserIDEQ applies the EQ predicate on the "haruki_user_id" field.
func HarukiUserIDEQ(v int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldHarukiUserID, v))
}

// HarukiUserIDNEQ applies the NEQ predicate on the "haruki_user_id" field.
func HarukiUserIDNEQ(v int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldHarukiUserID, v))
}

// HarukiUserIDIn applies the In predicate on the "haruki_user_id" field.
func HarukiUserIDIn(vs ...int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldHarukiUserID, vs...))
}

// HarukiUserIDNotIn applies the NotIn predicate on the "haruki_user_id" field.
func HarukiUserIDNotIn(vs ...int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldHarukiUserID, vs...))
}

// HarukiUserIDGT applies the GT predicate on the "haruki_user_id" field.
func HarukiUserIDGT(v int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldHarukiUserID, v))
}

// HarukiUserIDGTE applies the GTE predicate on the "haruki_user_id" field.
func HarukiUserIDGTE(v int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldHarukiUserID, v))
}

// HarukiUserIDLT applies the LT predicate on the "haruki_user_id" field.
func HarukiUserIDLT(v int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldHarukiUserID, v))
}

// HarukiUserIDLTE applies the LTE predicate on the "haruki_user_id" field.
func HarukiUserIDLTE(v int) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldHarukiUserID, v))
}

// OptionEQ applies the EQ predicate on the "option" field.
func OptionEQ(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldOption, v))
}

// OptionNEQ applies the NEQ predicate on the "option" field.
func OptionNEQ(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldOption, v))
}

// OptionIn applies the In predicate on the "option" field.
func OptionIn(vs ...string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldOption, vs...))
}

// OptionNotIn applies the NotIn predicate on the "option" field.
func OptionNotIn(vs ...string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldOption, vs...))
}

// OptionGT applies the GT predicate on the "option" field.
func OptionGT(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldOption, v))
}

// OptionGTE applies the GTE predicate on the "option" field.
func OptionGTE(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldOption, v))
}

// OptionLT applies the LT predicate on the "option" field.
func OptionLT(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldOption, v))
}

// OptionLTE applies the LTE predicate on the "option" field.
func OptionLTE(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldOption, v))
}

// OptionContains applies the Contains predicate on the "option" field.
func OptionContains(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldContains(FieldOption, v))
}

// OptionHasPrefix applies the HasPrefix predicate on the "option" field.
func OptionHasPrefix(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldHasPrefix(FieldOption, v))
}

// OptionHasSuffix applies the HasSuffix predicate on the "option" field.
func OptionHasSuffix(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldHasSuffix(FieldOption, v))
}

// OptionEqualFold applies the EqualFold predicate on the "option" field.
func OptionEqualFold(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEqualFold(FieldOption, v))
}

// OptionContainsFold applies the ContainsFold predicate on the "option" field.
func OptionContainsFold(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldContainsFold(FieldOption, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.UserPreference {
	return predicate.UserPreference(sql.FieldContainsFold(FieldValue, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserPreference) predicate.UserPreference {
	return predicate.UserPreference(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserPreference) predicate.UserPreference {
	return predicate.UserPreference(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserPreference) predicate.UserPreference {
	return predicate.UserPreference(sql.NotPredicates(p))
}
