// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "platform", Type: field.TypeString, Size: 20},
		{Name: "user_id", Type: field.TypeString, Size: 50},
		{Name: "ban_state", Type: field.TypeBool, Default: false},
		{Name: "ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "pjsk_ban_state", Type: field.TypeBool, Default: false},
		{Name: "pjsk_ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "chunithm_ban_state", Type: field.TypeBool, Default: false},
		{Name: "chunithm_ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "pjsk_main_ban_state", Type: field.TypeBool, Default: false},
		{Name: "pjsk_main_ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "pjsk_ranking_ban_state", Type: field.TypeBool, Default: false},
		{Name: "pjsk_ranking_ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "pjsk_alias_ban_state", Type: field.TypeBool, Default: false},
		{Name: "pjsk_alias_ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "pjsk_mysekai_ban_state", Type: field.TypeBool, Default: false},
		{Name: "pjsk_mysekai_ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "chunithm_main_ban_state", Type: field.TypeBool, Default: false},
		{Name: "chunithm_main_ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "chunithm_alias_ban_state", Type: field.TypeBool, Default: false},
		{Name: "chunithm_alias_ban_reason", Type: field.TypeString, Nullable: true, Size: 255},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_platform_user_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1], UsersColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
