// Code generated by ent, DO NOT EDIT.

package chunithmbinding

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the chunithmbinding type in the database.
	Label = "chunithm_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImID holds the string denoting the im_id field in the database.
	FieldImID = "im_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldServer holds the string denoting the server field in the database.
	FieldServer = "server"
	// FieldAimeID holds the string denoting the aime_id field in the database.
	FieldAimeID = "aime_id"
	// Table holds the table name of the chunithmbinding in the database.
	Table = "chunithm_bindings"
)

// Columns holds all SQL columns for chunithmbinding fields.
var Columns = []string{
	FieldID,
	FieldImID,
	FieldPlatform,
	FieldServer,
	FieldAimeID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ImIDValidator is a validator for the "im_id" field. It is called by the builders before save.
	ImIDValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// ServerValidator is a validator for the "server" field. It is called by the builders before save.
	ServerValidator func(string) error
	// AimeIDValidator is a validator for the "aime_id" field. It is called by the builders before save.
	AimeIDValidator func(string) error
)

// OrderOption defines the ordering options for the ChunithmBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImID orders the results by the im_id field.
func ByImID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByServer orders the results by the server field.
func ByServer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServer, opts...).ToFunc()
}

// ByAimeID orders the results by the aime_id field.
func ByAimeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAimeID, opts...).ToFunc()
}
