// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"
	"haruki-database/database/schema/bot"
)

// The DailyRequestsFunc type is an adapter to allow the use of ordinary
// function as DailyRequests mutator.
type DailyRequestsFunc func(context.Context, *bot.DailyRequestsMutation) (bot.Value, error)

// Mutate calls f(ctx, m).
func (f DailyRequestsFunc) Mutate(ctx context.Context, m bot.Mutation) (bot.Value, error) {
	if mv, ok := m.(*bot.DailyRequestsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bot.DailyRequestsMutation", m)
}

// The HourlyRequestsFunc type is an adapter to allow the use of ordinary
// function as HourlyRequests mutator.
type HourlyRequestsFunc func(context.Context, *bot.HourlyRequestsMutation) (bot.Value, error)

// Mutate calls f(ctx, m).
func (f HourlyRequestsFunc) Mutate(ctx context.Context, m bot.Mutation) (bot.Value, error) {
	if mv, ok := m.(*bot.HourlyRequestsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bot.HourlyRequestsMutation", m)
}

// The RequestsRankingFunc type is an adapter to allow the use of ordinary
// function as RequestsRanking mutator.
type RequestsRankingFunc func(context.Context, *bot.RequestsRankingMutation) (bot.Value, error)

// Mutate calls f(ctx, m).
func (f RequestsRankingFunc) Mutate(ctx context.Context, m bot.Mutation) (bot.Value, error) {
	if mv, ok := m.(*bot.RequestsRankingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bot.RequestsRankingMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *bot.UserMutation) (bot.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m bot.Mutation) (bot.Value, error) {
	if mv, ok := m.(*bot.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *bot.UserMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, bot.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m bot.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m bot.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m bot.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op bot.Op) Condition {
	return func(_ context.Context, m bot.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m bot.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m bot.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m bot.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk bot.Hook, cond Condition) bot.Hook {
	return func(next bot.Mutator) bot.Mutator {
		return bot.MutateFunc(func(ctx context.Context, m bot.Mutation) (bot.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, bot.Delete|bot.Create)
func On(hk bot.Hook, op bot.Op) bot.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, bot.Update|bot.UpdateOne)
func Unless(hk bot.Hook, op bot.Op) bot.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) bot.Hook {
	return func(bot.Mutator) bot.Mutator {
		return bot.MutateFunc(func(context.Context, bot.Mutation) (bot.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []bot.Hook {
//		return []bot.Hook{
//			Reject(bot.Delete|bot.Update),
//		}
//	}
func Reject(op bot.Op) bot.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []bot.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...bot.Hook) Chain {
	return Chain{append([]bot.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() bot.Hook {
	return func(mutator bot.Mutator) bot.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...bot.Hook) Chain {
	newHooks := make([]bot.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
