// Code generated by ent, DO NOT EDIT.

package pjsk

import (
	"context"
	"errors"
	"fmt"
	"haruki-database/database/schema/pjsk/aliasadmin"
	"haruki-database/database/schema/pjsk/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AliasAdminUpdate is the builder for updating AliasAdmin entities.
type AliasAdminUpdate struct {
	config
	hooks    []Hook
	mutation *AliasAdminMutation
}

// Where appends a list predicates to the AliasAdminUpdate builder.
func (_u *AliasAdminUpdate) Where(ps ...predicate.AliasAdmin) *AliasAdminUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AliasAdminUpdate) SetPlatform(v string) *AliasAdminUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AliasAdminUpdate) SetNillablePlatform(v *string) *AliasAdminUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetImID sets the "im_id" field.
func (_u *AliasAdminUpdate) SetImID(v string) *AliasAdminUpdate {
	_u.mutation.SetImID(v)
	return _u
}

// SetNillableImID sets the "im_id" field if the given value is not nil.
func (_u *AliasAdminUpdate) SetNillableImID(v *string) *AliasAdminUpdate {
	if v != nil {
		_u.SetImID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AliasAdminUpdate) SetName(v string) *AliasAdminUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AliasAdminUpdate) SetNillableName(v *string) *AliasAdminUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the AliasAdminMutation object of the builder.
func (_u *AliasAdminUpdate) Mutation() *AliasAdminMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AliasAdminUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AliasAdminUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AliasAdminUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AliasAdminUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AliasAdminUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := aliasadmin.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`pjsk: validator failed for field "AliasAdmin.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImID(); ok {
		if err := aliasadmin.ImIDValidator(v); err != nil {
			return &ValidationError{Name: "im_id", err: fmt.Errorf(`pjsk: validator failed for field "AliasAdmin.im_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := aliasadmin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`pjsk: validator failed for field "AliasAdmin.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AliasAdminUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aliasadmin.Table, aliasadmin.Columns, sqlgraph.NewFieldSpec(aliasadmin.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(aliasadmin.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImID(); ok {
		_spec.SetField(aliasadmin.FieldImID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aliasadmin.FieldName, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aliasadmin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AliasAdminUpdateOne is the builder for updating a single AliasAdmin entity.
type AliasAdminUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AliasAdminMutation
}

// SetPlatform sets the "platform" field.
func (_u *AliasAdminUpdateOne) SetPlatform(v string) *AliasAdminUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AliasAdminUpdateOne) SetNillablePlatform(v *string) *AliasAdminUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetImID sets the "im_id" field.
func (_u *AliasAdminUpdateOne) SetImID(v string) *AliasAdminUpdateOne {
	_u.mutation.SetImID(v)
	return _u
}

// SetNillableImID sets the "im_id" field if the given value is not nil.
func (_u *AliasAdminUpdateOne) SetNillableImID(v *string) *AliasAdminUpdateOne {
	if v != nil {
		_u.SetImID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AliasAdminUpdateOne) SetName(v string) *AliasAdminUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AliasAdminUpdateOne) SetNillableName(v *string) *AliasAdminUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the AliasAdminMutation object of the builder.
func (_u *AliasAdminUpdateOne) Mutation() *AliasAdminMutation {
	return _u.mutation
}

// Where appends a list predicates to the AliasAdminUpdate builder.
func (_u *AliasAdminUpdateOne) Where(ps ...predicate.AliasAdmin) *AliasAdminUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AliasAdminUpdateOne) Select(field string, fields ...string) *AliasAdminUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AliasAdmin entity.
func (_u *AliasAdminUpdateOne) Save(ctx context.Context) (*AliasAdmin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AliasAdminUpdateOne) SaveX(ctx context.Context) *AliasAdmin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AliasAdminUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AliasAdminUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AliasAdminUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := aliasadmin.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`pjsk: validator failed for field "AliasAdmin.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImID(); ok {
		if err := aliasadmin.ImIDValidator(v); err != nil {
			return &ValidationError{Name: "im_id", err: fmt.Errorf(`pjsk: validator failed for field "AliasAdmin.im_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := aliasadmin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`pjsk: validator failed for field "AliasAdmin.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AliasAdminUpdateOne) sqlSave(ctx context.Context) (_node *AliasAdmin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aliasadmin.Table, aliasadmin.Columns, sqlgraph.NewFieldSpec(aliasadmin.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`pjsk: missing "AliasAdmin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aliasadmin.FieldID)
		for _, f := range fields {
			if !aliasadmin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("pjsk: invalid field %q for query", f)}
			}
			if f != aliasadmin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(aliasadmin.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImID(); ok {
		_spec.SetField(aliasadmin.FieldImID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aliasadmin.FieldName, field.TypeString, value)
	}
	_node = &AliasAdmin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aliasadmin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
