// Code generated by ent, DO NOT EDIT.

package pjsk

import (
	"context"
	"errors"
	"fmt"
	"haruki-database/database/schema/pjsk/groupalias"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GroupAliasCreate is the builder for creating a GroupAlias entity.
type GroupAliasCreate struct {
	config
	mutation *GroupAliasMutation
	hooks    []Hook
}

// SetPlatform sets the "platform" field.
func (_c *GroupAliasCreate) SetPlatform(v string) *GroupAliasCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupAliasCreate) SetGroupID(v string) *GroupAliasCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAliasType sets the "alias_type" field.
func (_c *GroupAliasCreate) SetAliasType(v string) *GroupAliasCreate {
	_c.mutation.SetAliasType(v)
	return _c
}

// SetAliasTypeID sets the "alias_type_id" field.
func (_c *GroupAliasCreate) SetAliasTypeID(v int) *GroupAliasCreate {
	_c.mutation.SetAliasTypeID(v)
	return _c
}

// SetAlias sets the "alias" field.
func (_c *GroupAliasCreate) SetAlias(v string) *GroupAliasCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// Mutation returns the GroupAliasMutation object of the builder.
func (_c *GroupAliasCreate) Mutation() *GroupAliasMutation {
	return _c.mutation
}

// Save creates the GroupAlias in the database.
func (_c *GroupAliasCreate) Save(ctx context.Context) (*GroupAlias, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupAliasCreate) SaveX(ctx context.Context) *GroupAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupAliasCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupAliasCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupAliasCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`pjsk: missing required field "GroupAlias.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := groupalias.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`pjsk: validator failed for field "GroupAlias.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`pjsk: missing required field "GroupAlias.group_id"`)}
	}
	if v, ok := _c.mutation.GroupID(); ok {
		if err := groupalias.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`pjsk: validator failed for field "GroupAlias.group_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AliasType(); !ok {
		return &ValidationError{Name: "alias_type", err: errors.New(`pjsk: missing required field "GroupAlias.alias_type"`)}
	}
	if v, ok := _c.mutation.AliasType(); ok {
		if err := groupalias.AliasTypeValidator(v); err != nil {
			return &ValidationError{Name: "alias_type", err: fmt.Errorf(`pjsk: validator failed for field "GroupAlias.alias_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AliasTypeID(); !ok {
		return &ValidationError{Name: "alias_type_id", err: errors.New(`pjsk: missing required field "GroupAlias.alias_type_id"`)}
	}
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`pjsk: missing required field "GroupAlias.alias"`)}
	}
	if v, ok := _c.mutation.Alias(); ok {
		if err := groupalias.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`pjsk: validator failed for field "GroupAlias.alias": %w`, err)}
		}
	}
	return nil
}

func (_c *GroupAliasCreate) sqlSave(ctx context.Context) (*GroupAlias, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupAliasCreate) createSpec() (*GroupAlias, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupAlias{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupalias.Table, sqlgraph.NewFieldSpec(groupalias.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(groupalias.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(groupalias.FieldGroupID, field.TypeString, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.AliasType(); ok {
		_spec.SetField(groupalias.FieldAliasType, field.TypeString, value)
		_node.AliasType = value
	}
	if value, ok := _c.mutation.AliasTypeID(); ok {
		_spec.SetField(groupalias.FieldAliasTypeID, field.TypeInt, value)
		_node.AliasTypeID = value
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(groupalias.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	return _node, _spec
}

// GroupAliasCreateBulk is the builder for creating many GroupAlias entities in bulk.
type GroupAliasCreateBulk struct {
	config
	err      error
	builders []*GroupAliasCreate
}

// Save creates the GroupAlias entities in the database.
func (_c *GroupAliasCreateBulk) Save(ctx context.Context) ([]*GroupAlias, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupAlias, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupAliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupAliasCreateBulk) SaveX(ctx context.Context) []*GroupAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupAliasCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupAliasCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
