// Code generated by ent, DO NOT EDIT.

package pjsk

import (
	"context"
	"haruki-database/database/schema/pjsk/groupalias"
	"haruki-database/database/schema/pjsk/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GroupAliasDelete is the builder for deleting a GroupAlias entity.
type GroupAliasDelete struct {
	config
	hooks    []Hook
	mutation *GroupAliasMutation
}

// Where appends a list predicates to the GroupAliasDelete builder.
func (_d *GroupAliasDelete) Where(ps ...predicate.GroupAlias) *GroupAliasDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupAliasDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupAliasDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupAliasDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupalias.Table, sqlgraph.NewFieldSpec(groupalias.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupAliasDeleteOne is the builder for deleting a single GroupAlias entity.
type GroupAliasDeleteOne struct {
	_d *GroupAliasDelete
}

// Where appends a list predicates to the GroupAliasDelete builder.
func (_d *GroupAliasDeleteOne) Where(ps ...predicate.GroupAlias) *GroupAliasDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupAliasDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupalias.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupAliasDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
