// Code generated by ent, DO NOT EDIT.

package pjsk

import (
	"fmt"
	"haruki-database/database/schema/pjsk/pendingalias"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PendingAlias is the model entity for the PendingAlias schema.
type PendingAlias struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AliasType holds the value of the "alias_type" field.
	AliasType string `json:"alias_type,omitempty"`
	// AliasTypeID holds the value of the "alias_type_id" field.
	AliasTypeID int `json:"alias_type_id,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias string `json:"alias,omitempty"`
	// SubmittedBy holds the value of the "submitted_by" field.
	SubmittedBy string `json:"submitted_by,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt  time.Time `json:"submitted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PendingAlias) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pendingalias.FieldID, pendingalias.FieldAliasTypeID:
			values[i] = new(sql.NullInt64)
		case pendingalias.FieldAliasType, pendingalias.FieldAlias, pendingalias.FieldSubmittedBy:
			values[i] = new(sql.NullString)
		case pendingalias.FieldSubmittedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PendingAlias fields.
func (_m *PendingAlias) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pendingalias.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case pendingalias.FieldAliasType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias_type", values[i])
			} else if value.Valid {
				_m.AliasType = value.String
			}
		case pendingalias.FieldAliasTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field alias_type_id", values[i])
			} else if value.Valid {
				_m.AliasTypeID = int(value.Int64)
			}
		case pendingalias.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = value.String
			}
		case pendingalias.FieldSubmittedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_by", values[i])
			} else if value.Valid {
				_m.SubmittedBy = value.String
			}
		case pendingalias.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PendingAlias.
// This includes values selected through modifiers, order, etc.
func (_m *PendingAlias) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PendingAlias.
// Note that you need to call PendingAlias.Unwrap() before calling this method if this PendingAlias
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PendingAlias) Update() *PendingAliasUpdateOne {
	return NewPendingAliasClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PendingAlias entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PendingAlias) Unwrap() *PendingAlias {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("pjsk: PendingAlias is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PendingAlias) String() string {
	var builder strings.Builder
	builder.WriteString("PendingAlias(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("alias_type=")
	builder.WriteString(_m.AliasType)
	builder.WriteString(", ")
	builder.WriteString("alias_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AliasTypeID))
	builder.WriteString(", ")
	builder.WriteString("alias=")
	builder.WriteString(_m.Alias)
	builder.WriteString(", ")
	builder.WriteString("submitted_by=")
	builder.WriteString(_m.SubmittedBy)
	builder.WriteString(", ")
	builder.WriteString("submitted_at=")
	builder.WriteString(_m.SubmittedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PendingAliasSlice is a parsable slice of PendingAlias.
type PendingAliasSlice []*PendingAlias
