// Code generated by ent, DO NOT EDIT.

package pjsk

import (
	"fmt"
	"haruki-database/database/schema/pjsk/rejectedalias"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RejectedAlias is the model entity for the RejectedAlias schema.
type RejectedAlias struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AliasType holds the value of the "alias_type" field.
	AliasType string `json:"alias_type,omitempty"`
	// AliasTypeID holds the value of the "alias_type_id" field.
	AliasTypeID int `json:"alias_type_id,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias string `json:"alias,omitempty"`
	// ReviewedBy holds the value of the "reviewed_by" field.
	ReviewedBy string `json:"reviewed_by,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt   time.Time `json:"reviewed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RejectedAlias) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rejectedalias.FieldID, rejectedalias.FieldAliasTypeID:
			values[i] = new(sql.NullInt64)
		case rejectedalias.FieldAliasType, rejectedalias.FieldAlias, rejectedalias.FieldReviewedBy, rejectedalias.FieldReason:
			values[i] = new(sql.NullString)
		case rejectedalias.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RejectedAlias fields.
func (_m *RejectedAlias) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rejectedalias.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rejectedalias.FieldAliasType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias_type", values[i])
			} else if value.Valid {
				_m.AliasType = value.String
			}
		case rejectedalias.FieldAliasTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field alias_type_id", values[i])
			} else if value.Valid {
				_m.AliasTypeID = int(value.Int64)
			}
		case rejectedalias.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = value.String
			}
		case rejectedalias.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = value.String
			}
		case rejectedalias.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case rejectedalias.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RejectedAlias.
// This includes values selected through modifiers, order, etc.
func (_m *RejectedAlias) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RejectedAlias.
// Note that you need to call RejectedAlias.Unwrap() before calling this method if this RejectedAlias
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RejectedAlias) Update() *RejectedAliasUpdateOne {
	return NewRejectedAliasClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RejectedAlias entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RejectedAlias) Unwrap() *RejectedAlias {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("pjsk: RejectedAlias is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RejectedAlias) String() string {
	var builder strings.Builder
	builder.WriteString("RejectedAlias(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("alias_type=")
	builder.WriteString(_m.AliasType)
	builder.WriteString(", ")
	builder.WriteString("alias_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AliasTypeID))
	builder.WriteString(", ")
	builder.WriteString("alias=")
	builder.WriteString(_m.Alias)
	builder.WriteString(", ")
	builder.WriteString("reviewed_by=")
	builder.WriteString(_m.ReviewedBy)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("reviewed_at=")
	builder.WriteString(_m.ReviewedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RejectedAliasSlice is a parsable slice of RejectedAlias.
type RejectedAliasSlice []*RejectedAlias
