// Code generated by ent, DO NOT EDIT.

package pjsk

import (
	"context"
	"errors"
	"fmt"
	"haruki-database/database/schema/pjsk/userpreference"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPreferenceCreate is the builder for creating a UserPreference entity.
type UserPreferenceCreate struct {
	config
	mutation *UserPreferenceMutation
	hooks    []Hook
}

// SetImID sets the "im_id" field.
func (_c *UserPreferenceCreate) SetImID(v string) *UserPreferenceCreate {
	_c.mutation.SetImID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *UserPreferenceCreate) SetPlatform(v string) *UserPreferenceCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetOption sets the "option" field.
func (_c *UserPreferenceCreate) SetOption(v string) *UserPreferenceCreate {
	_c.mutation.SetOption(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *UserPreferenceCreate) SetValue(v string) *UserPreferenceCreate {
	_c.mutation.SetValue(v)
	return _c
}

// Mutation returns the UserPreferenceMutation object of the builder.
func (_c *UserPreferenceCreate) Mutation() *UserPreferenceMutation {
	return _c.mutation
}

// Save creates the UserPreference in the database.
func (_c *UserPreferenceCreate) Save(ctx context.Context) (*UserPreference, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPreferenceCreate) SaveX(ctx context.Context) *UserPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPreferenceCreate) check() error {
	if _, ok := _c.mutation.ImID(); !ok {
		return &ValidationError{Name: "im_id", err: errors.New(`pjsk: missing required field "UserPreference.im_id"`)}
	}
	if v, ok := _c.mutation.ImID(); ok {
		if err := userpreference.ImIDValidator(v); err != nil {
			return &ValidationError{Name: "im_id", err: fmt.Errorf(`pjsk: validator failed for field "UserPreference.im_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`pjsk: missing required field "UserPreference.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := userpreference.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`pjsk: validator failed for field "UserPreference.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Option(); !ok {
		return &ValidationError{Name: "option", err: errors.New(`pjsk: missing required field "UserPreference.option"`)}
	}
	if v, ok := _c.mutation.Option(); ok {
		if err := userpreference.OptionValidator(v); err != nil {
			return &ValidationError{Name: "option", err: fmt.Errorf(`pjsk: validator failed for field "UserPreference.option": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`pjsk: missing required field "UserPreference.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := userpreference.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`pjsk: validator failed for field "UserPreference.value": %w`, err)}
		}
	}
	return nil
}

func (_c *UserPreferenceCreate) sqlSave(ctx context.Context) (*UserPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPreferenceCreate) createSpec() (*UserPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpreference.Table, sqlgraph.NewFieldSpec(userpreference.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ImID(); ok {
		_spec.SetField(userpreference.FieldImID, field.TypeString, value)
		_node.ImID = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(userpreference.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Option(); ok {
		_spec.SetField(userpreference.FieldOption, field.TypeString, value)
		_node.Option = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(userpreference.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// UserPreferenceCreateBulk is the builder for creating many UserPreference entities in bulk.
type UserPreferenceCreateBulk struct {
	config
	err      error
	builders []*UserPreferenceCreate
}

// Save creates the UserPreference entities in the database.
func (_c *UserPreferenceCreateBulk) Save(ctx context.Context) ([]*UserPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPreferenceCreateBulk) SaveX(ctx context.Context) []*UserPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
