// Code generated by ent, DO NOT EDIT.

package chunithmdefaultserver

import (
	"haruki-database/database/schema/chunithm/maindb/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldLTE(FieldID, id))
}

// ImID applies equality check predicate on the "im_id" field. It's identical to ImIDEQ.
func ImID(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEQ(FieldImID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEQ(FieldPlatform, v))
}

// Server applies equality check predicate on the "server" field. It's identical to ServerEQ.
func Server(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEQ(FieldServer, v))
}

// ImIDEQ applies the EQ predicate on the "im_id" field.
func ImIDEQ(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEQ(FieldImID, v))
}

// ImIDNEQ applies the NEQ predicate on the "im_id" field.
func ImIDNEQ(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldNEQ(FieldImID, v))
}

// ImIDIn applies the In predicate on the "im_id" field.
func ImIDIn(vs ...string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldIn(FieldImID, vs...))
}

// ImIDNotIn applies the NotIn predicate on the "im_id" field.
func ImIDNotIn(vs ...string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldNotIn(FieldImID, vs...))
}

// ImIDGT applies the GT predicate on the "im_id" field.
func ImIDGT(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldGT(FieldImID, v))
}

// ImIDGTE applies the GTE predicate on the "im_id" field.
func ImIDGTE(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldGTE(FieldImID, v))
}

// ImIDLT applies the LT predicate on the "im_id" field.
func ImIDLT(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldLT(FieldImID, v))
}

// ImIDLTE applies the LTE predicate on the "im_id" field.
func ImIDLTE(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldLTE(FieldImID, v))
}

// ImIDContains applies the Contains predicate on the "im_id" field.
func ImIDContains(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldContains(FieldImID, v))
}

// ImIDHasPrefix applies the HasPrefix predicate on the "im_id" field.
func ImIDHasPrefix(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldHasPrefix(FieldImID, v))
}

// ImIDHasSuffix applies the HasSuffix predicate on the "im_id" field.
func ImIDHasSuffix(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldHasSuffix(FieldImID, v))
}

// ImIDEqualFold applies the EqualFold predicate on the "im_id" field.
func ImIDEqualFold(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEqualFold(FieldImID, v))
}

// ImIDContainsFold applies the ContainsFold predicate on the "im_id" field.
func ImIDContainsFold(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldContainsFold(FieldImID, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldContainsFold(FieldPlatform, v))
}

// ServerEQ applies the EQ predicate on the "server" field.
func ServerEQ(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEQ(FieldServer, v))
}

// ServerNEQ applies the NEQ predicate on the "server" field.
func ServerNEQ(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldNEQ(FieldServer, v))
}

// ServerIn applies the In predicate on the "server" field.
func ServerIn(vs ...string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldIn(FieldServer, vs...))
}

// ServerNotIn applies the NotIn predicate on the "server" field.
func ServerNotIn(vs ...string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldNotIn(FieldServer, vs...))
}

// ServerGT applies the GT predicate on the "server" field.
func ServerGT(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldGT(FieldServer, v))
}

// ServerGTE applies the GTE predicate on the "server" field.
func ServerGTE(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldGTE(FieldServer, v))
}

// ServerLT applies the LT predicate on the "server" field.
func ServerLT(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldLT(FieldServer, v))
}

// ServerLTE applies the LTE predicate on the "server" field.
func ServerLTE(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldLTE(FieldServer, v))
}

// ServerContains applies the Contains predicate on the "server" field.
func ServerContains(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldContains(FieldServer, v))
}

// ServerHasPrefix applies the HasPrefix predicate on the "server" field.
func ServerHasPrefix(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldHasPrefix(FieldServer, v))
}

// ServerHasSuffix applies the HasSuffix predicate on the "server" field.
func ServerHasSuffix(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldHasSuffix(FieldServer, v))
}

// ServerEqualFold applies the EqualFold predicate on the "server" field.
func ServerEqualFold(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldEqualFold(FieldServer, v))
}

// ServerContainsFold applies the ContainsFold predicate on the "server" field.
func ServerContainsFold(v string) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.FieldContainsFold(FieldServer, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChunithmDefaultServer) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChunithmDefaultServer) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChunithmDefaultServer) predicate.ChunithmDefaultServer {
	return predicate.ChunithmDefaultServer(sql.NotPredicates(p))
}
