name: Build HarukiDatabaseBackend

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for Multiple Platforms
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    strategy:
      matrix:
        platform: [windows-x64, linux-x64, linux-arm64, macos-arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.1

      - name: Build Executable and Compress
        run: |
          mkdir -p dist
          BIN_NAME=HarukiDatabaseBackend-${VERSION}-${{ matrix.platform }}
          case "${{ matrix.platform }}" in
            windows-x64)
              GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X=main.Version=${VERSION}" -o dist/${BIN_NAME}-Windows-x64.exe ./main.go
              # Create zip for Windows
              zip -j dist/${BIN_NAME}-Windows-x64.zip dist/${BIN_NAME}-Windows-x64.exe
              ;;
            linux-x64)
              GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X=main.Version=${VERSION}" -o dist/${BIN_NAME}-Linux-amd64 ./main.go
              # Create tar.gz for Linux
              tar -C dist -czf dist/${BIN_NAME}-Linux-amd64.tar.gz $(basename dist/${BIN_NAME}-Linux-amd64)
              ;;
            linux-arm64)
              GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X=main.Version=${VERSION}" -o dist/${BIN_NAME}-Linux-arm64 ./main.go
              tar -C dist -czf dist/${BIN_NAME}-Linux-arm64.tar.gz $(basename dist/${BIN_NAME}-Linux-arm64)
              ;;
            macos-arm64)
              GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X=main.Version=${VERSION}" -o dist/${BIN_NAME}-macOS-arm64 ./main.go
              tar -C dist -czf dist/${BIN_NAME}-macOS-arm64.tar.gz $(basename dist/${BIN_NAME}-macOS-arm64)
              ;;
          esac

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: HarukiDatabaseBackend-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
